### ISSUE TITLE
TO-do

### ISSUE THREAD

**Issue by LBuchananCates** [LBuchananCates/interactive-comment-section#1]
- [ ] append new div when submitting reply to comments (when i click "reply")
- [ ] ensure only ONE input form appears when click reply
- [ ] fix score event listener for up and down votes
